packages:
  - packages/*
  - docs
  - play
  - internal/*

catalog:
  '@ctrl/tinycolor': ^3.6.1
  '@element-plus/icons-vue': ^2.3.2
  '@floating-ui/dom': ^1.7.4
  '@popperjs/core': npm:@sxzz/popperjs-es@^2.11.7
  '@vitejs/plugin-vue': ^5.2.4
  '@vitejs/plugin-vue-jsx': ^4.2.0
  '@vue/server-renderer': ^3.5.26
  '@vue/shared': ^3.5.26
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^10.11.1
  lodash-unified: ^1.0.3
  normalize-wheel-es: ^1.2.0
  vue: ^3.5.26
  # vitest: ^2.0.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - es5-ext
  - esbuild
  - fsevents
  - puppeteer
  - vue-demi

overrides:
  jwa: ^1.4.2 # 20697
  typescript: $typescript

patchedDependencies:
  async-validator@4.2.5: patches/async-validator@4.2.5.patch #16757

peerDependencyRules:
  ignoreMissing:
    - vite
    - react
    - react-dom

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: false
